DOMAIN = "larmcentral"

CONF_ENTITY = "entity"
CONF_NAME = "name"
CONF_TRIGGER_STATE = "trigger_state"
CONF_START_LEVEL = "start_level"
CONF_RED_DELAY = "red_delay"
CONF_ENABLED = "enabled"
CONF_NOTIFY_RED = "notify_red"

LEVEL_YELLOW = "yellow"
LEVEL_RED = "red"

DEFAULT_TRIGGER_STATE = "on"
DEFAULT_START_LEVEL = LEVEL_YELLOW
DEFAULT_RED_DELAY = 5
DEFAULT_ENABLED = True
DEFAULT_NOTIFY_RED = True
